import {User} from './user/user.model';

export let usersData: User[] = [
    {
        'id': 1,
        'firstName': 'Aram',
        'lastName': 'Tadevosyan',
        'middleName': '',
        'email': 'example@mail.com',
        'phoneNumber': '+37494824242',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '06/10/2006',
        'profileImgUrl': 'https://smthng.com/img1.png',
        'language': 'Armenian',
        'nationality': 'Armenian',
        'recitations': ''
    },
    {
        'id': 2,
        'firstName': 'Sarah',
        'lastName': 'Jackson',
        'middleName': '',
        'email': 'something@mail.com',
        'phoneNumber': '+15031439812',
        'gender': 'female',
        'isActivated': true,
        'birthDate': '03/29/1998',
        'profileImgUrl': 'https://smthng.com/img2.png',
        'language': 'English',
        'nationality': 'American',
        'recitations': ''
    },
    {
        'id': 3,
        'firstName': 'Sun',
        'lastName': 'Liang',
        'middleName': '',
        'email': 'example3@mail.com',
        'phoneNumber': '+38233546356',
        'gender': 'male',
        'isActivated': false,
        'birthDate': '11/14/1974',
        'profileImgUrl': 'https://smthng.com/img5.png',
        'language': 'Chinese',
        'nationality': 'Chinese',
        'recitations': ''
    },
    {
        'id': 4,
        'firstName': 'Jean',
        'lastName': 'Legrand',
        'middleName': '',
        'email': 'some@mail.com',
        'phoneNumber': '+33123484523',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '09/26/1989',
        'profileImgUrl': 'https://smthng.com/img344.png',
        'language': 'French',
        'nationality': 'French',
        'recitations': 'recitations'
    },
    {
        'id': 5,
        'firstName': 'Vazgen',
        'lastName': 'Urumyan',
        'middleName': '',
        'email': 'vazgurum@mail.com',
        'phoneNumber': '+37477142424',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '01/19/2001',
        'profileImgUrl': 'https://smthng.com/vzgurum234.png',
        'language': 'Armenian',
        'nationality': 'Armenian',
        'recitations': ''
    },
    {
        'id': 6,
        'firstName': 'Michelle',
        'lastName': 'White',
        'middleName': '',
        'email': 'mwhite@mail.com',
        'phoneNumber': '+12323983113',
        'gender': 'female',
        'isActivated': false,
        'birthDate': '12/07/1997',
        'profileImgUrl': 'https://websiteexample.com/img7.png',
        'language': 'English',
        'nationality': 'Irish',
        'recitations': ''
    },
    {
        'id': 7,
        'firstName': 'Jean',
        'lastName': 'Legrand',
        'middleName': '',
        'email': 'some@mail.com',
        'phoneNumber': '+33123484523',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '09/26/1989',
        'profileImgUrl': 'https://smthng.com/img344.png',
        'language': 'French',
        'nationality': 'French',
        'recitations': 'recitations'
    },
    {
        'id': 8,
        'firstName': 'Sun',
        'lastName': 'Liang',
        'middleName': '',
        'email': 'example3@mail.com',
        'phoneNumber': '+38233546356',
        'gender': 'male',
        'isActivated': false,
        'birthDate': '11/14/1974',
        'profileImgUrl': 'https://smthng.com/img5.png',
        'language': 'Chinese',
        'nationality': 'Chinese',
        'recitations': ''
    },
    {
        'id': 9,
        'firstName': 'Sarah',
        'lastName': 'Jackson',
        'middleName': '',
        'email': 'something@mail.com',
        'phoneNumber': '+15031439812',
        'gender': 'female',
        'isActivated': true,
        'birthDate': '03/29/1998',
        'profileImgUrl': 'https://smthng.com/img2.png',
        'language': 'English',
        'nationality': 'American',
        'recitations': ''
    },
    {
        'id': 10,
        'firstName': 'Aram',
        'lastName': 'Tadevosyan',
        'middleName': '',
        'email': 'example@mail.com',
        'phoneNumber': '+37494824242',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '06/10/2006',
        'profileImgUrl': 'https://smthng.com/img1.png',
        'language': 'Armenian',
        'nationality': 'Armenian',
        'recitations': ''
    },
    {
        'id': 11,
        'firstName': 'Sun',
        'lastName': 'Liang',
        'middleName': '',
        'email': 'example3@mail.com',
        'phoneNumber': '+38233546356',
        'gender': 'male',
        'isActivated': false,
        'birthDate': '11/14/1974',
        'profileImgUrl': 'https://smthng.com/img5.png',
        'language': 'Chinese',
        'nationality': 'Chinese',
        'recitations': ''
    },
    {
        'id': 12,
        'firstName': 'Sarah',
        'lastName': 'Jackson',
        'middleName': '',
        'email': 'something@mail.com',
        'phoneNumber': '+15031439812',
        'gender': 'female',
        'isActivated': true,
        'birthDate': '03/29/1998',
        'profileImgUrl': 'https://smthng.com/img2.png',
        'language': 'English',
        'nationality': 'American',
        'recitations': ''
    },
    {
        'id': 13,
        'firstName': 'Vazgen',
        'lastName': 'Urumyan',
        'middleName': '',
        'email': 'vazgurum@mail.com',
        'phoneNumber': '+37477142424',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '01/19/2001',
        'profileImgUrl': 'https://smthng.com/vzgurum234.png',
        'language': 'Armenian',
        'nationality': 'Armenian',
        'recitations': ''
    },
    {
        'id': 14,
        'firstName': 'Jean',
        'lastName': 'Legrand',
        'middleName': '',
        'email': 'some@mail.com',
        'phoneNumber': '+33123484523',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '09/26/1989',
        'profileImgUrl': 'https://smthng.com/img344.png',
        'language': 'French',
        'nationality': 'French',
        'recitations': 'recitations'
    },
    {
        'id': 15,
        'firstName': 'Michelle',
        'lastName': 'White',
        'middleName': '',
        'email': 'mwhite@mail.com',
        'phoneNumber': '+12323983113',
        'gender': 'female',
        'isActivated': false,
        'birthDate': '12/07/1997',
        'profileImgUrl': 'https://websiteexample.com/img7.png',
        'language': 'English',
        'nationality': 'Irish',
        'recitations': ''
    },
    {
        'id': 16,
        'firstName': 'Jean',
        'lastName': 'Legrand',
        'middleName': '',
        'email': 'some@mail.com',
        'phoneNumber': '+33123484523',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '09/26/1989',
        'profileImgUrl': 'https://smthng.com/img344.png',
        'language': 'French',
        'nationality': 'French',
        'recitations': 'recitations'
    },
    {
        'id': 17,
        'firstName': 'Sun',
        'lastName': 'Liang',
        'middleName': '',
        'email': 'example3@mail.com',
        'phoneNumber': '+38233546356',
        'gender': 'male',
        'isActivated': false,
        'birthDate': '11/14/1974',
        'profileImgUrl': 'https://smthng.com/img5.png',
        'language': 'Chinese',
        'nationality': 'Chinese',
        'recitations': ''
    },
    {
        'id': 18,
        'firstName': 'Sarah',
        'lastName': 'Jackson',
        'middleName': '',
        'email': 'something@mail.com',
        'phoneNumber': '+15031439812',
        'gender': 'female',
        'isActivated': true,
        'birthDate': '03/29/1998',
        'profileImgUrl': 'https://smthng.com/img2.png',
        'language': 'English',
        'nationality': 'American',
        'recitations': ''
    },
    {
        'id': 19,
        'firstName': 'Sun',
        'lastName': 'Liang',
        'middleName': '',
        'email': 'example3@mail.com',
        'phoneNumber': '+38233546356',
        'gender': 'male',
        'isActivated': false,
        'birthDate': '11/14/1974',
        'profileImgUrl': 'https://smthng.com/img5.png',
        'language': 'Chinese',
        'nationality': 'Chinese',
        'recitations': ''
    },
    {
        'id': 20,
        'firstName': 'Jean',
        'lastName': 'Legrand',
        'middleName': '',
        'email': 'some@mail.com',
        'phoneNumber': '+33123484523',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '09/26/1989',
        'profileImgUrl': 'https://smthng.com/img344.png',
        'language': 'French',
        'nationality': 'French',
        'recitations': 'recitations'
    },
    {
        'id': 21,
        'firstName': 'Vazgen',
        'lastName': 'Urumyan',
        'middleName': '',
        'email': 'vazgurum@mail.com',
        'phoneNumber': '+37477142424',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '01/19/2001',
        'profileImgUrl': 'https://smthng.com/vzgurum234.png',
        'language': 'Armenian',
        'nationality': 'Armenian',
        'recitations': ''
    },
    {
        'id': 22,
        'firstName': 'Sarah',
        'lastName': 'Jackson',
        'middleName': '',
        'email': 'something@mail.com',
        'phoneNumber': '+15031439812',
        'gender': 'female',
        'isActivated': true,
        'birthDate': '03/29/1998',
        'profileImgUrl': 'https://smthng.com/img2.png',
        'language': 'English',
        'nationality': 'American',
        'recitations': ''
    },
    {
        'id': 23,
        'firstName': 'Aram',
        'lastName': 'Tadevosyan',
        'middleName': '',
        'email': 'example@mail.com',
        'phoneNumber': '+37494824242',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '06/10/2006',
        'profileImgUrl': 'https://smthng.com/img1.png',
        'language': 'Armenian',
        'nationality': 'Armenian',
        'recitations': ''
    },
    {
        'id': 24,
        'firstName': 'Sun',
        'lastName': 'Liang',
        'middleName': '',
        'email': 'example3@mail.com',
        'phoneNumber': '+38233546356',
        'gender': 'male',
        'isActivated': false,
        'birthDate': '11/14/1974',
        'profileImgUrl': 'https://smthng.com/img5.png',
        'language': 'Chinese',
        'nationality': 'Chinese',
        'recitations': ''
    },
    {
        'id': 25,
        'firstName': 'Sarah',
        'lastName': 'Jackson',
        'middleName': '',
        'email': 'something@mail.com',
        'phoneNumber': '+15031439812',
        'gender': 'female',
        'isActivated': true,
        'birthDate': '03/29/1998',
        'profileImgUrl': 'https://smthng.com/img2.png',
        'language': 'English',
        'nationality': 'American',
        'recitations': ''
    },
    {
        'id': 26,
        'firstName': 'Vazgen',
        'lastName': 'Urumyan',
        'middleName': '',
        'email': 'vazgurum@mail.com',
        'phoneNumber': '+37477142424',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '01/19/2001',
        'profileImgUrl': 'https://smthng.com/vzgurum234.png',
        'language': 'Armenian',
        'nationality': 'Armenian',
        'recitations': ''
    },
    {
        'id': 27,
        'firstName': 'Jean',
        'lastName': 'Legrand',
        'middleName': '',
        'email': 'some@mail.com',
        'phoneNumber': '+33123484523',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '09/26/1989',
        'profileImgUrl': 'https://smthng.com/img344.png',
        'language': 'French',
        'nationality': 'French',
        'recitations': 'recitations'
    },
    {
        'id': 28,
        'firstName': 'Michelle',
        'lastName': 'White',
        'middleName': '',
        'email': 'mwhite@mail.com',
        'phoneNumber': '+12323983113',
        'gender': 'female',
        'isActivated': false,
        'birthDate': '12/07/1997',
        'profileImgUrl': 'https://websiteexample.com/img7.png',
        'language': 'English',
        'nationality': 'Irish',
        'recitations': ''
    },
    {
        'id': 29,
        'firstName': 'Aram',
        'lastName': 'Tadevosyan',
        'middleName': '',
        'email': 'example@mail.com',
        'phoneNumber': '+37494824242',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '06/10/2006',
        'profileImgUrl': 'https://smthng.com/img1.png',
        'language': 'Armenian',
        'nationality': 'Armenian',
        'recitations': ''
    },
    {
        'id': 30,
        'firstName': 'Sarah',
        'lastName': 'Jackson',
        'middleName': '',
        'email': 'something@mail.com',
        'phoneNumber': '+15031439812',
        'gender': 'female',
        'isActivated': true,
        'birthDate': '03/29/1998',
        'profileImgUrl': 'https://smthng.com/img2.png',
        'language': 'English',
        'nationality': 'American',
        'recitations': ''
    },
    {
        'id': 31,
        'firstName': 'Sun',
        'lastName': 'Liang',
        'middleName': '',
        'email': 'example3@mail.com',
        'phoneNumber': '+38233546356',
        'gender': 'male',
        'isActivated': false,
        'birthDate': '11/14/1974',
        'profileImgUrl': 'https://smthng.com/img5.png',
        'language': 'Chinese',
        'nationality': 'Chinese',
        'recitations': ''
    },
    {
        'id': 32,
        'firstName': 'Jean',
        'lastName': 'Legrand',
        'middleName': '',
        'email': 'some@mail.com',
        'phoneNumber': '+33123484523',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '09/26/1989',
        'profileImgUrl': 'https://smthng.com/img344.png',
        'language': 'French',
        'nationality': 'French',
        'recitations': 'recitations'
    },
    {
        'id': 33,
        'firstName': 'Vazgen',
        'lastName': 'Urumyan',
        'middleName': '',
        'email': 'vazgurum@mail.com',
        'phoneNumber': '+37477142424',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '01/19/2001',
        'profileImgUrl': 'https://smthng.com/vzgurum234.png',
        'language': 'Armenian',
        'nationality': 'Armenian',
        'recitations': ''
    },
    {
        'id': 34,
        'firstName': 'Michelle',
        'lastName': 'White',
        'middleName': '',
        'email': 'mwhite@mail.com',
        'phoneNumber': '+12323983113',
        'gender': 'female',
        'isActivated': false,
        'birthDate': '12/07/1997',
        'profileImgUrl': 'https://websiteexample.com/img7.png',
        'language': 'English',
        'nationality': 'Irish',
        'recitations': ''
    },
    {
        'id': 35,
        'firstName': 'Jean',
        'lastName': 'Legrand',
        'middleName': '',
        'email': 'some@mail.com',
        'phoneNumber': '+33123484523',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '09/26/1989',
        'profileImgUrl': 'https://smthng.com/img344.png',
        'language': 'French',
        'nationality': 'French',
        'recitations': 'recitations'
    },
    {
        'id': 36,
        'firstName': 'Sun',
        'lastName': 'Liang',
        'middleName': '',
        'email': 'example3@mail.com',
        'phoneNumber': '+38233546356',
        'gender': 'male',
        'isActivated': false,
        'birthDate': '11/14/1974',
        'profileImgUrl': 'https://smthng.com/img5.png',
        'language': 'Chinese',
        'nationality': 'Chinese',
        'recitations': ''
    },
    {
        'id': 37,
        'firstName': 'Sarah',
        'lastName': 'Jackson',
        'middleName': '',
        'email': 'something@mail.com',
        'phoneNumber': '+15031439812',
        'gender': 'female',
        'isActivated': true,
        'birthDate': '03/29/1998',
        'profileImgUrl': 'https://smthng.com/img2.png',
        'language': 'English',
        'nationality': 'American',
        'recitations': ''
    },
    {
        'id': 38,
        'firstName': 'Aram',
        'lastName': 'Tadevosyan',
        'middleName': '',
        'email': 'example@mail.com',
        'phoneNumber': '+37494824242',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '06/10/2006',
        'profileImgUrl': 'https://smthng.com/img1.png',
        'language': 'Armenian',
        'nationality': 'Armenian',
        'recitations': ''
    },
    {
        'id': 39,
        'firstName': 'Sun',
        'lastName': 'Liang',
        'middleName': '',
        'email': 'example3@mail.com',
        'phoneNumber': '+38233546356',
        'gender': 'male',
        'isActivated': false,
        'birthDate': '11/14/1974',
        'profileImgUrl': 'https://smthng.com/img5.png',
        'language': 'Chinese',
        'nationality': 'Chinese',
        'recitations': ''
    },
    {
        'id': 40,
        'firstName': 'Sarah',
        'lastName': 'Jackson',
        'middleName': '',
        'email': 'something@mail.com',
        'phoneNumber': '+15031439812',
        'gender': 'female',
        'isActivated': true,
        'birthDate': '03/29/1998',
        'profileImgUrl': 'https://smthng.com/img2.png',
        'language': 'English',
        'nationality': 'American',
        'recitations': ''
    },
    {
        'id': 41,
        'firstName': 'Vazgen',
        'lastName': 'Urumyan',
        'middleName': '',
        'email': 'vazgurum@mail.com',
        'phoneNumber': '+37477142424',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '01/19/2001',
        'profileImgUrl': 'https://smthng.com/vzgurum234.png',
        'language': 'Armenian',
        'nationality': 'Armenian',
        'recitations': ''
    },
    {
        'id': 42,
        'firstName': 'Jean',
        'lastName': 'Legrand',
        'middleName': '',
        'email': 'some@mail.com',
        'phoneNumber': '+33123484523',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '09/26/1989',
        'profileImgUrl': 'https://smthng.com/img344.png',
        'language': 'French',
        'nationality': 'French',
        'recitations': 'recitations'
    },
    {
        'id': 43,
        'firstName': 'Michelle',
        'lastName': 'White',
        'middleName': '',
        'email': 'mwhite@mail.com',
        'phoneNumber': '+12323983113',
        'gender': 'female',
        'isActivated': false,
        'birthDate': '12/07/1997',
        'profileImgUrl': 'https://websiteexample.com/img7.png',
        'language': 'English',
        'nationality': 'Irish',
        'recitations': ''
    },
    {
        'id': 44,
        'firstName': 'Jean',
        'lastName': 'Legrand',
        'middleName': '',
        'email': 'some@mail.com',
        'phoneNumber': '+33123484523',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '09/26/1989',
        'profileImgUrl': 'https://smthng.com/img344.png',
        'language': 'French',
        'nationality': 'French',
        'recitations': 'recitations'
    },
    {
        'id': 45,
        'firstName': 'Sun',
        'lastName': 'Liang',
        'middleName': '',
        'email': 'example3@mail.com',
        'phoneNumber': '+38233546356',
        'gender': 'male',
        'isActivated': false,
        'birthDate': '11/14/1974',
        'profileImgUrl': 'https://smthng.com/img5.png',
        'language': 'Chinese',
        'nationality': 'Chinese',
        'recitations': ''
    },
    {
        'id': 46,
        'firstName': 'Sarah',
        'lastName': 'Jackson',
        'middleName': '',
        'email': 'something@mail.com',
        'phoneNumber': '+15031439812',
        'gender': 'female',
        'isActivated': true,
        'birthDate': '03/29/1998',
        'profileImgUrl': 'https://smthng.com/img2.png',
        'language': 'English',
        'nationality': 'American',
        'recitations': ''
    },
    {
        'id': 47,
        'firstName': 'Sun',
        'lastName': 'Liang',
        'middleName': '',
        'email': 'example3@mail.com',
        'phoneNumber': '+38233546356',
        'gender': 'male',
        'isActivated': false,
        'birthDate': '11/14/1974',
        'profileImgUrl': 'https://smthng.com/img5.png',
        'language': 'Chinese',
        'nationality': 'Chinese',
        'recitations': ''
    },
    {
        'id': 48,
        'firstName': 'Jean',
        'lastName': 'Legrand',
        'middleName': '',
        'email': 'some@mail.com',
        'phoneNumber': '+33123484523',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '09/26/1989',
        'profileImgUrl': 'https://smthng.com/img344.png',
        'language': 'French',
        'nationality': 'French',
        'recitations': 'recitations'
    },
    {
        'id': 49,
        'firstName': 'Vazgen',
        'lastName': 'Urumyan',
        'middleName': '',
        'email': 'vazgurum@mail.com',
        'phoneNumber': '+37477142424',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '01/19/2001',
        'profileImgUrl': 'https://smthng.com/vzgurum234.png',
        'language': 'Armenian',
        'nationality': 'Armenian',
        'recitations': ''
    },
    {
        'id': 50,
        'firstName': 'Sarah',
        'lastName': 'Jackson',
        'middleName': '',
        'email': 'something@mail.com',
        'phoneNumber': '+15031439812',
        'gender': 'female',
        'isActivated': true,
        'birthDate': '03/29/1998',
        'profileImgUrl': 'https://smthng.com/img2.png',
        'language': 'English',
        'nationality': 'American',
        'recitations': ''
    },
    {
        'id': 51,
        'firstName': 'Aram',
        'lastName': 'Tadevosyan',
        'middleName': '',
        'email': 'example@mail.com',
        'phoneNumber': '+37494824242',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '06/10/2006',
        'profileImgUrl': 'https://smthng.com/img1.png',
        'language': 'Armenian',
        'nationality': 'Armenian',
        'recitations': ''
    },
    {
        'id': 52,
        'firstName': 'Sun',
        'lastName': 'Liang',
        'middleName': '',
        'email': 'example3@mail.com',
        'phoneNumber': '+38233546356',
        'gender': 'male',
        'isActivated': false,
        'birthDate': '11/14/1974',
        'profileImgUrl': 'https://smthng.com/img5.png',
        'language': 'Chinese',
        'nationality': 'Chinese',
        'recitations': ''
    },
    {
        'id': 53,
        'firstName': 'Sarah',
        'lastName': 'Jackson',
        'middleName': '',
        'email': 'something@mail.com',
        'phoneNumber': '+15031439812',
        'gender': 'female',
        'isActivated': true,
        'birthDate': '03/29/1998',
        'profileImgUrl': 'https://smthng.com/img2.png',
        'language': 'English',
        'nationality': 'American',
        'recitations': ''
    },
    {
        'id': 54,
        'firstName': 'Vazgen',
        'lastName': 'Urumyan',
        'middleName': '',
        'email': 'vazgurum@mail.com',
        'phoneNumber': '+37477142424',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '01/19/2001',
        'profileImgUrl': 'https://smthng.com/vzgurum234.png',
        'language': 'Armenian',
        'nationality': 'Armenian',
        'recitations': ''
    },
    {
        'id': 55,
        'firstName': 'Jean',
        'lastName': 'Legrand',
        'middleName': '',
        'email': 'some@mail.com',
        'phoneNumber': '+33123484523',
        'gender': 'male',
        'isActivated': true,
        'birthDate': '09/26/1989',
        'profileImgUrl': 'https://smthng.com/img344.png',
        'language': 'French',
        'nationality': 'French',
        'recitations': 'recitations'
    },
    {
        'id': 56,
        'firstName': 'Michelle',
        'lastName': 'White',
        'middleName': '',
        'email': 'mwhite@mail.com',
        'phoneNumber': '+12323983113',
        'gender': 'female',
        'isActivated': false,
        'birthDate': '12/07/1997',
        'profileImgUrl': 'https://websiteexample.com/img7.png',
        'language': 'English',
        'nationality': 'Irish',
        'recitations': ''
    }
];